### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by stranger1200** [Ravbug/QReaper#9]
Hey there, I'm a completely noob at coding but I'm getting an error when trying to run the bot, not sure what I'm doing wrong.

```
TypeError: Cannot read properties of undefined (reading 'id')
    at ClientDataManager.newChannel (/Users/username/Downloads/QReaper-master/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/Users/username/Downloads/QReaper-master/node_modules/discord.js/src/structures/Guild.js:206:68)
    at GuildCreateHandler.handle (/Users/username/Downloads/QReaper-master/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/Users/username/Downloads/QReaper-master/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/Users/username/Downloads/QReaper-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/Users/username/Downloads/QReaper-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/Users/username/Downloads/QReaper-master/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/Users/username/Downloads/QReaper-master/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:519:28)
```

Help would be appreciated, thanks!

**Comment by Ravbug** [comment]
You probably need to update DiscordJS. Note that I'm not working on this project anymore so it might still be broken after updating it.

**Comment by stranger1200** [comment]
Still broken, thanks anyways I guess
